apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
      evaluation_interval: 1s

    scrape_configs:
      # Scrape du propre Prometheus
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape Kafka (Strimzi)
      - job_name: 'kafka'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_strimzi_io_kind]
            regex: Kafka
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: tcp-prometheus
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      # Scrape pods "consumers" avec label app=latency
      - job_name: 'latency'
        metrics_path: /prometheus
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: latency
            action: keep
          # Garde les pods ayant un port nommé "metrics" ou "prometheus"
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: prometheus|metrics|brom
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      # Scrape des pods "workload" exposant les métriques Prometheus
      - job_name: 'workload'
        metrics_path: /prometheus
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Garde uniquement les pods avec le label app=producer
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: workload
            action: keep
          # Garde les pods ayant un port nommé "metrics" ou "prometheus"
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: prometheus|metrics|brom
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
            
      # Scrape de l'exporter custom
      - job_name: 'binscale-exporter'
        metrics_path: /prometheus
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Garde uniquement les pods avec le label app=exporter
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: exporter
            action: keep
          # Garde les pods ayant un port nommé "metrics" ou "prometheus"
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: prometheus|metrics|brom
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
