

apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: default
data:
  controller-config.yaml: |
    topics:
      - from: latency-ehanced-1
        to: latency-ehanced-2
        weight: 0.2
      - from: latency-ehanced-1
        to: latency-ehanced-3
        weight: 0.8
      - from: latency-ehanced-2
        to: latency-ehanced-5
        weight: 0.2
      - from: latency-ehanced-3
        to: latency-ehanced-5
        weight: 1
      - from: latency-ehanced-3
        to: latency-ehanced-4
        weight: 0.2
      - from: latency-ehanced-4
        to: latency-ehanced-5
        weight: 1
    nodes:
      - name: latency-ehanced-1
        wsla: 500
        maxConsumptionRate: 200
        inputTopic: topic-latency-ehanced-1
        partitionNumber: 10
        groupId: latencyehancedgroup1
      - name: latency-ehanced-2
        wsla: 500
        maxConsumptionRate: 200
        inputTopic: topic-latency-ehanced-2
        partitionNumber: 10
        groupId: latencyehancedgroup2
      - name: latency-ehanced-3
        wsla: 500
        maxConsumptionRate: 200
        inputTopic: topic-latency-ehanced-3
        partitionNumber: 10
        groupId: latencyehancedgroup3
      - name: latency-ehanced-4
        wsla: 500
        maxConsumptionRate: 200
        inputTopic: topic-latency-ehanced-4
        partitionNumber: 10
        groupId: latencyehancedgroup4
      - name: latency-ehanced-5
        wsla: 500
        maxConsumptionRate: 200
        inputTopic: topic-latency-ehanced-5
        partitionNumber: 10
        groupId: latencyehancedgroup5
---
apiVersion: v1
kind: Pod
metadata:
  name: controllerandscaler
  namespace: default
  labels:
    app: controllerandscaler
    context: experience
spec:
  serviceAccountName: admin-service-account
  restartPolicy: Always
  containers:
    - name: controllerandscaler
      image: docker.io/benneuville/binscale:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 5002
      env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: NUMBER_PARTITIONS
          value: "20"
        - name: INIT_SIZE
          value: "1"
        - name: SCALING_STRATEGY
          value: "ehanced"
        - name: FUP
          value: "0.9"
        - name: FDOWN
          value: "0.5"
        - name: REB_TIME
          value: "0.4"
        - name: DI
          value: "1500"
        - name: REQUEST_TIME_RANGE
          value: "5"
        - name: REQUEST_TIME_UNIT
          value: "s"
        - name: DEBUG_OPTIONS
          value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
          
        - name: TOPICS_CONFIG_PATH
          value: "/config/controller-config.yaml"
          
      command: ["sh", "-c", "java $DEBUG_OPTIONS -jar /app/Controller.jar"]
      volumeMounts:
        - name: controller-config
          mountPath: /config
  volumes:
    - name: controller-config
      configMap:
        name: controller-config
---
apiVersion: v1
kind: Service
metadata:
  name: controllerandscaler
  namespace: default
spec:
  selector:
    app: controllerandscaler
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002