

apiVersion: v1
kind: ConfigMap
metadata:
  name: latencyehancedgroup1-config
  namespace: default
data:
  latencyehancedgroup1.yaml: |
    output:

    - name: topic-latency-ehanced-2
      ratio: 0.2 

    - name: topic-latency-ehanced-3
      ratio: 0.8 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-ehanced-1
  namespace: default
  labels:
    app: latency
    instance: latency-ehanced-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-ehanced-1
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-ehanced-1
            - name: GROUP_ID
              value: latencyehancedgroup1
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: CONSUMPTION_RATE
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"


            - name: PROCESSING_STRATEGY
              value: "custom"

            - name: TOPICS_DISTRIBUTION_CONFIG_PATH
              value: "/config/latencyehancedgroup1.yaml"
          volumeMounts:
            - name: latencyehancedgroup1-config
              mountPath: /config
      volumes:
        - name: latencyehancedgroup1-config
          configMap:
            name: latencyehancedgroup1-config

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: latencyehancedgroup2-config
  namespace: default
data:
  latencyehancedgroup2.yaml: |
    output:

    - name: topic-latency-ehanced-5
      ratio: 0.2 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-ehanced-2
  namespace: default
  labels:
    app: latency
    instance: latency-ehanced-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-ehanced-2
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-ehanced-2
            - name: GROUP_ID
              value: latencyehancedgroup2
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: CONSUMPTION_RATE
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"


            - name: PROCESSING_STRATEGY
              value: "custom"

            - name: TOPICS_DISTRIBUTION_CONFIG_PATH
              value: "/config/latencyehancedgroup2.yaml"
          volumeMounts:
            - name: latencyehancedgroup2-config
              mountPath: /config
      volumes:
        - name: latencyehancedgroup2-config
          configMap:
            name: latencyehancedgroup2-config

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: latencyehancedgroup3-config
  namespace: default
data:
  latencyehancedgroup3.yaml: |
    output:

    - name: topic-latency-ehanced-5
      ratio: 1 

    - name: topic-latency-ehanced-4
      ratio: 0.2 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-ehanced-3
  namespace: default
  labels:
    app: latency
    instance: latency-ehanced-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-ehanced-3
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-ehanced-3
            - name: GROUP_ID
              value: latencyehancedgroup3
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: CONSUMPTION_RATE
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"


            - name: PROCESSING_STRATEGY
              value: "custom"

            - name: TOPICS_DISTRIBUTION_CONFIG_PATH
              value: "/config/latencyehancedgroup3.yaml"
          volumeMounts:
            - name: latencyehancedgroup3-config
              mountPath: /config
      volumes:
        - name: latencyehancedgroup3-config
          configMap:
            name: latencyehancedgroup3-config

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: latencyehancedgroup4-config
  namespace: default
data:
  latencyehancedgroup4.yaml: |
    output:

    - name: topic-latency-ehanced-5
      ratio: 1 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-ehanced-4
  namespace: default
  labels:
    app: latency
    instance: latency-ehanced-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-ehanced-4
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-ehanced-4
            - name: GROUP_ID
              value: latencyehancedgroup4
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: CONSUMPTION_RATE
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"


            - name: PROCESSING_STRATEGY
              value: "custom"

            - name: TOPICS_DISTRIBUTION_CONFIG_PATH
              value: "/config/latencyehancedgroup4.yaml"
          volumeMounts:
            - name: latencyehancedgroup4-config
              mountPath: /config
      volumes:
        - name: latencyehancedgroup4-config
          configMap:
            name: latencyehancedgroup4-config

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-ehanced-5
  namespace: default
  labels:
    app: latency
    instance: latency-ehanced-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-ehanced-5
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-ehanced-5
            - name: GROUP_ID
              value: latencyehancedgroup5
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: CONSUMPTION_RATE
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"


---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demoobservabilitypodmonitor
  labels:
    app: strimzi
  namespace: default
spec:
  selector:
    matchLabels:
      app: latency
#    matchExpressions:
#      - key: app
#        operator: In
#        values:
#            - "latency-ehanced-1"
#            - "latency-ehanced-2"
#            - "latency-ehanced-3"
#            - "latency-ehanced-4"
#            - "latency-ehanced-5"
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - path: /prometheus
      port: brom
      interval: 1s