

apiVersion: v1
kind: ConfigMap
metadata:
  name: latencygroup1-config
  namespace: default
data:
  latencygroup1.yaml: |
    output:

    - name: topic-latency-2
      ratio: 0.2 

    - name: topic-latency-3
      ratio: 0.8 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-1
  namespace: default
  labels:
    app: latency
    instance: latency-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-1
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-1
            - name: GROUP_ID
              value: latencygroup1
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: MAX_POLL_RECORDS
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"

            - name: PROCESSING_STRATEGY
              value: "custom"

            - name: TOPICS_DISTRIBUTION_CONFIG_PATH
              value: "/config/latencygroup1.yaml"
          volumeMounts:
            - name: latencygroup1-config
              mountPath: /config
      volumes:
        - name: latencygroup1-config
          configMap:
            name: latencygroup1-config

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: latencygroup2-config
  namespace: default
data:
  latencygroup2.yaml: |
    output:

    - name: topic-latency-6
      ratio: 0.8 

    - name: topic-latency-5
      ratio: 0.2 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-2
  namespace: default
  labels:
    app: latency
    instance: latency-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-2
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-2
            - name: GROUP_ID
              value: latencygroup2
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: MAX_POLL_RECORDS
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"

            - name: TOPICS_DISTRIBUTION_CONFIG_PATH
              value: "/config/latencygroup2.yaml"
          volumeMounts:
            - name: latencygroup2-config
              mountPath: /config
      volumes:
        - name: latencygroup2-config
          configMap:
            name: latencygroup2-config

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: latencygroup3-config
  namespace: default
data:
  latencygroup3.yaml: |
    output:

    - name: topic-latency-5
      ratio: 1 

    - name: topic-latency-4
      ratio: 0.2 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-3
  namespace: default
  labels:
    app: latency
    instance: latency-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-3
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-3
            - name: GROUP_ID
              value: latencygroup3
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: MAX_POLL_RECORDS
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"

            - name: TOPICS_DISTRIBUTION_CONFIG_PATH
              value: "/config/latencygroup3.yaml"
          volumeMounts:
            - name: latencygroup3-config
              mountPath: /config
      volumes:
        - name: latencygroup3-config
          configMap:
            name: latencygroup3-config

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: latencygroup4-config
  namespace: default
data:
  latencygroup4.yaml: |
    output:

    - name: topic-latency-5
      ratio: 1 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-4
  namespace: default
  labels:
    app: latency
    instance: latency-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-4
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-4
            - name: GROUP_ID
              value: latencygroup4
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: MAX_POLL_RECORDS
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"

            - name: TOPICS_DISTRIBUTION_CONFIG_PATH
              value: "/config/latencygroup4.yaml"
          volumeMounts:
            - name: latencygroup4-config
              mountPath: /config
      volumes:
        - name: latencygroup4-config
          configMap:
            name: latencygroup4-config

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-5
  namespace: default
  labels:
    app: latency
    instance: latency-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-5
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-5
            - name: GROUP_ID
              value: latencygroup5
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: MAX_POLL_RECORDS
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-6
  namespace: default
  labels:
    app: latency
    instance: latency-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency-6
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/consumer.jar"]
          ports:
            - containerPort: 8080
              name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-6
            - name: GROUP_ID
              value: latencygroup6
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: MAX_POLL_RECORDS
              value: "200"
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"
            - name: TIME_TO_COMMIT
              value: "50"
            - name: WSLA
              value: "500"
            - name: ASYNC_COMMIT
              value: "False"

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demoobservabilitypodmonitor
  labels:
    app: strimzi
  namespace: default
spec:
  selector:
    matchLabels:
      app: latency
#    matchExpressions:
#      - key: app
#        operator: In
#        values:
#            - "latency-1"
#            - "latency-2"
#            - "latency-3"
#            - "latency-4"
#            - "latency-5"
#            - "latency-6"
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - path: /prometheus
      port: brom
      interval: 1s