apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-1
  namespace: default
  labels:
    app: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-1
  template:
    metadata:
      labels:
        app: workload-1
    spec:
      containers:
        - name: java-kafka-producer
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/producer.jar"]
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-1
            - name: PARTITION_WEIGHTS
              value: "1,1,1,1,1,1,1,1,1,1"
            - name: DELAY_MS
              value: "600"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PRODUCER_ACKS
              value: "0"
            - name: ADDITIONAL_CONFIG
              value: |
                retries=100
# NOT REQUIERED DECLARED VARIABLES
            - name: WORKLOAD
              value: "biased" # "constant", "biased", "non_uniform"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-2
  namespace: default
  labels:
    app: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-2
  template:
    metadata:
      labels:
        app: workload-2
    spec:
      containers:
        - name: java-kafka-producer
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "/app/producer.jar"]
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: topic-latency-2
            - name: PARTITION_WEIGHTS
              value: "1,1,1,1,1,1,1,1,1,1"
            - name: DELAY_MS
              value: "600"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PRODUCER_ACKS
              value: "0"
            - name: ADDITIONAL_CONFIG
              value: |
                retries=100
# NOT REQUIERED DECLARED VARIABLES
            - name: WORKLOAD
              value: "biased" # "constant", "biased", "non_uniform"