

apiVersion: batch/v1
kind: Job
metadata:
  name: workload-ehanced-1
  namespace: default
  labels:
    app: workload
    context: experience
spec:
  template:
    metadata:
      labels:
        app: workload
        context: experience
    spec:
      containers:
        - name: java-kafka-producer
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "$(JAVA_OPTS)", "-jar", "/app/producer.jar"]
          env:
            - name: JAVA_OPTS
              value: "-Dnetworkaddress.cache.ttl=0 -Dnetworkaddress.cache.negative.ttl=0"
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: PRODUCER_ID
              value: "workload-ehanced-1"
            - name: TOPIC
              value: topic-latency-ehanced-1
            - name: PARTITION_WEIGHTS
              value: "1,1,1,1,1,1,1,1,1,1"
            - name: DELAY_MS
              value: "600"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PRODUCER_ACKS
              value: "0"
            - name: ADDITIONAL_CONFIG
              value: |
                retries=100
            - name: WORKLOAD
              value: "biased"
            - name: INPUT_WORKLOAD
              value: "spike-n-decrease.csv"
      restartPolicy: Never
  backoffLimit: 0
---


apiVersion: batch/v1
kind: Job
metadata:
  name: workload-ehanced-2
  namespace: default
  labels:
    app: workload
    context: experience
spec:
  template:
    metadata:
      labels:
        app: workload
        context: experience
    spec:
      containers:
        - name: java-kafka-producer
          image: docker.io/benneuville/binscale:latest
          imagePullPolicy: Always
          command: ["java", "$(JAVA_OPTS)", "-jar", "/app/producer.jar"]
          env:
            - name: JAVA_OPTS
              value: "-Dnetworkaddress.cache.ttl=0 -Dnetworkaddress.cache.negative.ttl=0"
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: PRODUCER_ID
              value: "workload-ehanced-2"
            - name: TOPIC
              value: topic-latency-ehanced-2
            - name: PARTITION_WEIGHTS
              value: "1,1,1,1,1,1,1,1,1,1"
            - name: DELAY_MS
              value: "600"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PRODUCER_ACKS
              value: "0"
            - name: ADDITIONAL_CONFIG
              value: |
                retries=100
            - name: WORKLOAD
              value: "biased"
            - name: INPUT_WORKLOAD
              value: "defaultArrivalRatesm.csv"
      restartPolicy: Never
  backoffLimit: 0