apiVersion: v1
kind: Pod
metadata:
  labels:
    app: workload
  name: workload
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: java-kafka-producer
      image: docker.io/laaziz2001/producer:1.0
      env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: TOPIC
          value: testtopic1
        - name: DELAY_MS
          value: "1000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PRODUCER_ACKS
          value: "0"
        - name: ADDITIONAL_CONFIG
          value: |
                retries=100

---

apiVersion: v1
kind: Pod
metadata:
    labels:
      app: grpcassignmentserver
    name: controllerandscaler
    namespace: default
spec:
  serviceAccountName: admin-service-account
  restartPolicy: Always
  containers:
    - name: controllerandscaler
      image: docker.io/laaziz2001/controller:1.0
      ports:
      - containerPort: 5002
      env:
      - name: BOOTSTRAP_SERVERS
        value: my-cluster-kafka-bootstrap:9092
      - name: FUP
        value: "0.9"
      - name: MU
        value: "200"
      - name: WSLA
        value: "0.5"
      - name: FDOWN
        value: "0.4"
      - name: REB_TIME
        value: "0.05"
      - name: DI
        value: "1000"
---

apiVersion: v1
kind: Service
metadata:
  name: assignmentservice
  namespace: default
spec:
  selector:
        app: workload
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002

---

apiVersion: v1
kind: Service
metadata:
  name: rateservice
  namespace: default
spec:
  selector:
        app: latency
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latency
  name: latency
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
        - name: latency
          image: docker.io/laaziz2001/consumer:1.0
          ports:
          - containerPort: 8080
            name: brom
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: testtopic1
            - name: GROUP_ID
              value: testgroup1
            - name: SLEEP
              value: "5"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=500
            - name: SCALE
              value: "3"
            - name: SHAPE
              value: "2.75"

---

  apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: demoobservabilitypodmonitor
    labels:
      app: strimzi
    namespace: default
  spec:
    selector:
      matchLabels:
        app: latency
    namespaceSelector:
      matchNames:
        - default
    podMetricsEndpoints:
      - path: /prometheus
        port: brom
        interval: 5s
