apiVersion: v1
kind: Pod
metadata:
  labels:
    app: workload
  name: workload
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: java-kafka-producer
      image: 134.59.131.201:5000/experience_fab
      # image: 134.59.131.235:5000/experience-2024-04-21
      imagePullPolicy: IfNotPresent
      command: ["java", "-jar", "/app/producer.jar"]
      env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: TOPIC
          value: testtopic1
        - name: DELAY_MS
          value: "1000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PRODUCER_ACKS
          value: "0"
        - name: ADDITIONAL_CONFIG
          value: |
            retries=100