- name: Deploy Application
  hosts: localhost

  tasks:
    - name: Apply Admin Service Account for ControllerAndScaler Pod
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/service-account.yaml

    - name: Apply Role Binding
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/role-binding.yaml

    - name: Apply Deployment
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/deployment.yml
