---
- name: Deploy Kafka Cluster (Strimzi 0.45.1)
  hosts: localhost

  tasks:
    - name: Apply Strimzi Operator (version 0.45.1)
      command: >
        kubectl create -f
        https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.45.1/strimzi-cluster-operator-0.45.1.yaml
        -n default

    - name: Apply Kafka Cluster definition (my-cluster)
      command: kubectl apply -f ../kubernetes/kafka-cluster.yaml -n default

    - name: Apply Kafka Node Pool definition
      command: kubectl apply -f ../kubernetes/kafka-nodepool.yaml -n default

    - name: Apply Kafka Topic
      command: kubectl apply -f ../kubernetes/kafka-topic.yaml -n default

    - name: Check Kafka Cluster Readiness
      command: kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n default


- name: Deploy Prometheus, Grafana, and related resources
  hosts: localhost

  tasks:
    - name: Apply Prometheus Operator Deployment
      command: kubectl apply -f ../kubernetes/prometheus-operator-deployment.yaml -n default

    - name: Apply Prometheus Additional Configuration
      command: kubectl apply -f ../kubernetes/prometheus-additional.yaml -n default

    - name: Apply Prometheus Rules
      command: kubectl apply -f ../kubernetes/prometheus-rules.yaml -n default

    - name: Apply Strimzi Pod Monitor
      command: kubectl apply -f ../kubernetes/strimzi-pod-monitor.yaml -n default

    - name: Apply Prometheus Configuration
      command: kubectl apply -f ../kubernetes/prometheus.yaml -n default

    - name: Apply Prometheus Service
      command: kubectl apply -f ../kubernetes/prometheus-service.yaml -n default


- name: Deploy Elastic Stack
  hosts: localhost

  tasks:
    - name: Create elastic namespace (if not exists)
      command: kubectl create namespace elastic
      ignore_errors: yes

    - name: Apply Filebeat
      command: kubectl apply -f ../elastic-stack/filebeat-kubernetes.yaml -n elastic
