---
- name: Deploy Application
  hosts: localhost
  become: false
  vars:
    namespace: default
    timeout: 180s

  tasks:

    - name: Delete Filebeat
      command: kubectl delete -f ../filebeat/filebeat-kubernetes.yaml -n elastic --ignore-not-found=true
    - name: Launch Filebeat
      command: kubectl apply -f ../filebeat/filebeat-kubernetes.yaml -n elastic
    - name: Wait 100s
      pause:
        seconds: 100

    - name: WARM UP - Pre-pull Image
      command: kubectl apply -f ../experience/generated/pre-pull-image.yaml

    - name: Apply Admin Service Account for ControllerAndScaler Pod
      command: kubectl apply -f ../kubernetes/service-account.yaml

    - name: Apply Role Binding
      command: kubectl apply -f ../kubernetes/role-binding.yaml

    - name: Apply Topics Definition
      command: kubectl apply -f ../experience/generated/kafka-topics.yaml

    - name: Controller Deployment
      command: kubectl apply -f ../experience/generated/controller.yaml

    - name: Waiting for Controller
      command: kubectl wait pod -l app=controllerandscaler --for=condition=Ready --timeout={{ timeout }} -n {{ namespace }}
      register: controller_ready
      failed_when: controller_ready.rc != 0

    - name: Consumer Deployment (latency)
      command: kubectl apply -f ../experience/generated/latency.yaml

    - name: Waiting for consumer
      command: kubectl wait deployment -l app=latency --for=condition=Available --timeout={{ timeout }} -n {{ namespace }}
      register: consumer_ready
      failed_when: consumer_ready.rc != 0
      
    - name: Producer Deployment (workload)
      command: kubectl apply -f ../experience/generated/workload.yaml
