---
- name: Deploy Application
  hosts: localhost

  tasks:
    - name: Apply Admin Service Account for ControllerAndScaler Pod
      command: kubectl apply -f ../kubernetes/service-account.yaml

    - name: Apply Role Binding
      command: kubectl apply -f ../kubernetes/role-binding.yaml

    - name: Apply Deployment
      command: kubectl apply -f ../kubernetes/deployment.yml