---
- name: Clean up previous deployments
  hosts: localhost
  become: false
  vars:
    namespace: default

  tasks:
    - name: Delete Controller Pod and Service
      command: kubectl delete -f ../experience/controller.yaml -n {{ namespace }} --ignore-not-found=true

    - name: Delete Latency Deployment and PodMonitor
      command: kubectl delete -f ../experience/latency.yaml -n {{ namespace }} --ignore-not-found=true

    - name: Delete Producer Deployment and Service
      command: kubectl delete -f ../experience/producer.yaml -n {{ namespace }} --ignore-not-found=true
