---
- name: Clean up previous deployments
  hosts: localhost
  become: false
  vars:
    namespace: default

  tasks:
    - name: Delete Filebeat
      command: kubectl delete -f ../filebeat/filebeat-kubernetes.yaml -n elastic --ignore-not-found=true
    - name: Delete Controller Pod and Service
      command: kubectl delete -f ../experience/controller.yaml -n {{ namespace }} --ignore-not-found=true

    - name: Delete Latency Deployment and PodMonitor
      command: kubectl delete -f ../experience/generated/latency.yaml -n {{ namespace }} --ignore-not-found=true

    - name: Delete Producer Deployment and Service
      command: kubectl delete -f ../experience/generated/workload.yaml -n {{ namespace }} --ignore-not-found=true